CAMERA_INDEX = 0
MAX_HANDS = 1
DETECTION_CONFIDENCE = 0.7
TRACKING_CONFIDENCE = 0.7

PINCH_DISTANCE_THRESHOLD = 0.4
OPEN_DISTANCE_THRESHOLD = 1.3
FIST_DISTANCE_THRESHOLD = 1.3
MIN_CONFIDENCE = 0.5

HOLD_FRAMES = 8
COOLDOWN_SECONDS = 1.5

ACTION_MAP = {
    "pinch": "next_slide",
    "fist": "previous_slide",
    "open": "toggle_mute",
}

START_WITH_ACTIONS_ENABLED = False

WINDOW_NAME = "Gesture Controller"
QUIT_KEY = "q"
TOGGLE_ACTIONS_KEY = "e"